name: "ec2-deploy"
on:
  push:
    branches:
      - master

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
     - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_IP }}  >> ~/.ssh/known_hosts

    - name: Install dependencies on production server and run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.PROD_DEPLOY_DIR }}
          echo "$(date) Hello from ec2" >> output.txt  