name: "ec2-deploy"
on:
  push:
    branches:
      - master

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST_IP }}  >> ~/.ssh/known_hosts

      - name: Install dependencies on production server and run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "$(date) Hello from Github Actions" >> ~/output.txt
            cd ${{ secrets.PROD_DEPLOY_DIR }}
            git checkout master 
            git fetch origin master 
            git reset --hard origin/master
            npm install
            npm run build-demo
            echo "$(date) GA exits EC2\n" >> ~/output.txt
